### ISSUE TITLE
question~

### ISSUE THREAD

**Issue by CXSunshine** [LDOUBLEV/semi-supervised-GAN#1]
Hello，
   when I run the code，I have some touble in understanding the errors that the program generated.
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 28, in main
    model.train()
  File "F:\pythonprogram\semi-supervised-GAN-master\train.py", line 132, in train
    plot.flush()
  File "F:\pythonprogram\semi-supervised-GAN-master\vlib\plot.py", line 37, in flush
    prints.append("{}\t{}".format(name, np.mean(vals.values())))
  File "C:\Users\admin\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 2957, in mean
    out=out, **kwargs)
  File "C:\Users\admin\Anaconda3\lib\site-packages\numpy\core\_methods.py", line 82, in _mean
    ret = ret / rcount
TypeError: unsupported operand type(s) for /: 'dict_values' and 'int'

Can you help me solve this problem？

**Comment by CXSunshine** [comment]
I just get the test accuracy 0.5333，not the 0.99？

**Comment by LDOUBLEV** [comment]
@CXSunshine hi, I fine-tune the code by loading trained weights for MNIST generation. the final weights in model_saved file  have higher test accuracy, you can test it. on the other side , the d loss function is something wrong. i made some change. i will test it when i have free time. and it is glad to get your advice to help me improve the code.

**Comment by CXSunshine** [comment]
ok，i will have a try.
Progress together！hahah~

**Comment by wudongya1226** [comment]
@CXSunshine @LDOUBLEV 
I also have the same mistakes as you. 
TypeError: unsupported operand type(s) for /: 'dict_values' and 'int'
Could you please tell me how do you solve it?
